<a href="https://colab.research.google.com/github/subrat008/DMDW-LAB-/blob/main/assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

df=pd.read_csv('/content/Book1.csv')

In [ ]:
df

    roll gen  age branch sec
0      1   m   20    cse   a
1      2   m   20    bca   a
2      3   m   19    bba   b
3      4   m   20    cse   c
4      5   m   19    cse   d
5      6   f   19    bba   d
6      7   f   20    bca   a
7      8   f   20    bba   c
8      9   m   20    bca   d
9     10   f   20    bca   b
10    11   m   20    bca   b
11    12   f   19    cse   d
12    13   f   19    cse   d
13    14   f   20    cse   a
14    15   m   19    bba   b

In [ ]:
df.head()

   roll gen  age branch sec
0     1   m   20    cse   a
1     2   m   20    bca   a
2     3   m   19    bba   b
3     4   m   20    cse   c
4     5   m   19    cse   d

In [ ]:
df.tail()

    roll gen  age branch sec
10    11   m   20    bca   b
11    12   f   19    cse   d
12    13   f   19    cse   d
13    14   f   20    cse   a
14    15   m   19    bba   b

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    15 non-null     int64
 1   gen     15 non-null     object
 2   age     15 non-null     int64
 3   branch  15 non-null     object
 4   sec     15 non-null     object
dtypes: int64(2), object(3)
memory usage: 732.0+ bytes

In [ ]:
df.describe()

            roll        age
count  15.000000  15.000000
mean    8.000000  19.600000
std     4.472136   0.507093
min     1.000000  19.000000
25%     4.500000  19.000000
50%     8.000000  20.000000
75%    11.500000  20.000000
max    15.000000  20.000000

In [ ]:
df.columns

Index(['roll', 'gen', 'age', 'branch', 'sec'], dtype='object')

In [ ]:
df.dtypes

roll       int64
gen       object
age        int64
branch    object
sec       object
dtype: object

In [ ]:
df.isnull()

     roll    gen    age  branch    sec
0   False  False  False   False  False
1   False  False  False   False  False
2   False  False  False   False  False
3   False  False  False   False  False
4   False  False  False   False  False
5   False  False  False   False  False
6   False  False  False   False  False
7   False  False  False   False  False
8   False  False  False   False  False
9   False  False  False   False  False
10  False  False  False   False  False
11  False  False  False   False  False
12  False  False  False   False  False
13  False  False  False   False  False
14  False  False  False   False  False

In [ ]:
df.isnull().sum()

roll      0
gen       0
age       0
branch    0
sec       0
dtype: int64

In [ ]:
df.iloc[0]

roll        1
gen         m
age        20
branch    cse
sec         a
Name: 0, dtype: object

In [ ]:
df.loc(0)

In [ ]:
ages = df['age']
ages

0     20
1     20
2     19
3     20
4     19
5     19
6     20
7     20
8     20
9     20
10    20
11    19
12    19
13    20
14    19
Name: age, dtype: int64

In [ ]:
adults=df[df['age']>19]
print("those whose are elder than 20 years \n", adults)

those whose are elder than 20 years
     roll gen  age branch sec
0      1   m   20    cse   a
1      2   m   20    bca   a
3      4   m   20    cse   c
6      7   f   20    bca   a
7      8   f   20    bba   c
8      9   m   20    bca   d
9     10   f   20    bca   b
10    11   m   20    bca   b
13    14   f   20    cse   a

In [ ]:
df[(df['age']>=19) & (df['age'] <= 20)]['age']

0     20
1     20
2     19
3     20
4     19
5     19
6     20
7     20
8     20
9     20
10    20
11    19
12    19
13    20
14    19
Name: age, dtype: int64